#!/usr/bin/env python3
"""Artifact-hygiene rail (c40).

The repo's own CI GENERATES files inside the checkout:
  - scripts/workflow-pins... no: the composite-exec step writes
    `composite-run.sh` (extracted verbatim from action.yml) and redirects
    the verifier output to `step.log`; the JS-parity step writes
    `js-proof-parity.md`. Since c25 the first two were ACCIDENTALLY
    COMMITTED (a local test run of the extraction + negative case staged
    the byproducts): the repo shipped a committed `step.log` whose bytes
    are the error output of one throwaway negative-control run
    ('error: [Errno 2] ... no-such-receipt.md'). Nothing referenced
    either file; the Pages build (legacy, branch main, root) served both
    at public URLs. This rail pins the invariant so the class cannot
    come back silently:

  A. BLOCKLIST: no generated-file name may ever be tracked again.
  B. SCRATCH SWEEP: no tracked *.log / *.out at any depth (the step.log
     class generalized by extension, not just by name).
  C. DOC DENOMINATOR: any tracked .md outside proofs/ must be named in
     DOC_ALLOW (README.md only today). A new tracked .md that is neither
     a receipt nor a doc goes RED (the accidental js-proof-parity.md
     class, caught even if someone renamed it off the blocklist).

Exit codes: 0 clean, 1 a violation is printed, 2 bad usage.
"""
import subprocess
import sys

# Files the CI harness WRITES inside the checkout. They must never be
# tracked (git ls-files) -- their presence in a fresh checkout is by
# construction, their presence in git is an accident.
BLOCKLIST = {
    "composite-run.sh",   # extracted verbatim from action.yml at CI time
    "step.log",           # composite-exec verifier stdout
    "js-proof-parity.md", # JS<->Py parity receipt (already gitignored)
    "proof.md",           # signed-proof round-trip scratch
    "vermin.log",         # py39-floor vermin stdout
}

# Tracked .md files outside proofs/ must be enumerated here (docs).
DOC_ALLOW = {"README.md"}


def tracked_files():
    r = subprocess.run(["git", "ls-files"], capture_output=True, text=True)
    if r.returncode != 0:
        print("FAIL: git ls-files failed: " + r.stderr.strip())
        sys.exit(2)
    return r.stdout.split()


def main():
    if len(sys.argv) > 1:
        print(__doc__.strip().splitlines()[-1])
        return 2
    fails = 0
    files = tracked_files()

    # A. generated-file blocklist
    hits = sorted(set(files) & BLOCKLIST)
    for h in hits:
        print(f"FAIL: generated CI byproduct is tracked: {h}")
        fails += 1
    if not hits:
        print(f"OK: 0/{len(BLOCKLIST)} generated byproducts tracked")

    # B. scratch-name sweep: any tracked *.log / *.out at any depth
    scratch = sorted(f for f in files if f.endswith((".log", ".out")))
    for s in scratch:
        print(f"FAIL: tracked scratch log: {s}")
        fails += 1
    if not scratch:
        print("OK: no tracked *.log / *.out anywhere")

    # C. tracked .md outside proofs/ must be an allowed doc
    stray = sorted(
        f for f in files
        if f.endswith(".md") and not f.startswith("proofs/")
        and f not in DOC_ALLOW
    )
    for s in stray:
        print(f"FAIL: tracked .md outside proofs/ not in DOC_ALLOW: {s}")
        fails += 1
    if not stray:
        print("OK: tracked .md set == proofs/ receipts + DOC_ALLOW docs")

    if fails:
        print(f"artifact-hygiene: {fails} violation(s)")
        return 1
    print("artifact-hygiene: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
