#!/usr/bin/env python3
"""Artifact-hygiene rail (c40).

The repo's own CI GENERATES files inside the checkout:
  - scripts/workflow-pins... no: the composite-exec step writes
    `composite-run.sh` (extracted verbatim from action.yml) and redirects
    the verifier output to `step.log`; the JS-parity step writes
    `js-proof-parity.md`. Since c25 the first two were ACCIDENTALLY
    COMMITTED (a local test run of the extraction + negative case staged
    the byproducts): the repo shipped a committed `step.log` whose bytes
    are the error output of one throwaway negative-control run
    ('error: [Errno 2] ... no-such-receipt.md'). Nothing referenced
    either file; the Pages build (legacy, branch main, root) served both
    at public URLs. This rail pins the invariant so the class cannot
    come back silently:

  A. BLOCKLIST: no generated-file name may ever be tracked again.
  B. SCRATCH SWEEP: no tracked *.log / *.out at any depth (the step.log
     class generalized by extension, not just by name).
  C. DOC DENOMINATOR: any tracked .md outside proofs/ must be named in
     DOC_ALLOW (README.md only today). A new tracked .md that is neither
     a receipt nor a doc goes RED (the accidental js-proof-parity.md
     class, caught even if someone renamed it off the blocklist).
  D. CHECKOUT-PATH INVENTORY (A c50 delta, c44): every job-level
     `actions/checkout` with a relative `path:` WRITES a whole directory
     into the checkout at CI time — this repo's own shared workflow
     (verify-release.yml `path: .ethkey-tools`) is such a write, and the
     name was in NEITHER leg-A set nor .gitignore. Instead of trusting a
     hand-maintained list, leg D DERIVES the prefix set from the workflow
     YAML text and marks every tracked file under one RED. Same rule for
     the whole fleet: an actions/checkout path: is a generated byproduct
     by definition, so it belongs in the inventory by derivation, not by
     somebody remembering to add it (A c50 're-derive YOUR inventory'
     lesson made machine-enforced).
  E. CATCH-VS-PREVENT PARITY (B c44 offer, c49): a BLOCKLIST name CATCHES
     the accident at rail time; an .gitignore line PREVENTS it (a bare
     `git add -A` skips it). Every leg-A name must score rc=0 from
     `git check-ignore --no-index -q`, and every leg-D derived prefix must
     have a PROBE CHILD that scores rc=0 (a dir-only rule never matches
     the bare dir name — measured: '.ethkey-tools/' rc=0, '.ethkey-tools'
     rc=1 — so the probe is `<prefix>probe`, A c55 child-path shape).
     check-ignore rc>1 = the authority itself broke -> exit 2 WITH THE
     NAME (c43 rule: a crashing rail must not masquerade as a verdict).
     Without E, my c44 proof.md ignore-line fix was a one-time hand-close:
     nothing asserted the NEXT blocklist entry would carry one.

Exit codes: 0 clean, 1 a violation is printed, 2 bad usage or broken
check-ignore authority.
"""
import os
import subprocess
import sys

# Files the CI harness WRITES inside the checkout. They must never be
# tracked (git ls-files) -- their presence in a fresh checkout is by
# construction, their presence in git is an accident.
# DECLARED AS frozenset ON PURPOSE (A c54 class, measured red on my shape):
# a bare `{...}` literal is a SET only while non-empty — the moment a
# leg-A cleanup removes the last name it silently becomes a EMPTY DICT,
# and `set(files) & {}` dies TypeError on the first CI run after the
# cleanup commit. `frozenset()` keeps set semantics at the empty
# boundary, and the harness F8/F8m pair pins both directions (empty =
# GREEN; empty bare-braces = the crash the declaration prevents).
BLOCKLIST = frozenset({
    "composite-run.sh",   # extracted verbatim from action.yml at CI time
    "step.log",           # composite-exec verifier stdout
    "js-proof-parity.md", # JS<->Py parity receipt (already gitignored)
    "proof.md",           # signed-proof round-trip scratch
    "vermin.log",         # py39-floor vermin stdout
})

# Tracked .md files outside proofs/ must be enumerated here (docs).
# Same declaration rule as BLOCKLIST: never rely on `{}` meaning 'set'.
DOC_ALLOW = frozenset({"README.md"})


def tracked_files():
    r = subprocess.run(["git", "ls-files"], capture_output=True, text=True)
    if r.returncode != 0:
        print("FAIL: git ls-files failed: " + r.stderr.strip())
        sys.exit(2)
    return r.stdout.split()


def checkout_paths():
    """D: derive the in-checkout `actions/checkout path:` prefixes from the
    workflow/action YAML TEXT (stdlib line-scan; PyYAML is NOT on the runner
    -- c21 lesson). A path: line counts only when it belongs to a checkout
    `with:` block: seen within 4 lines AFTER a `uses: actions/checkout`
    line, indented deeper than that uses: line. Returns a set of normalized
    relative prefixes; `${{`-templated or absolute paths are skipped from
    matching (can't resolve text) but printed as a NOTE so they can never
    hide silently."""
    prefixes, unresolvable = set(), []
    for root, dirs, files in os.walk(".github"):
        dirs[:] = [d for d in dirs if d != ".git"]
        for fn in files:
            if not fn.endswith((".yml", ".yaml")):
                continue
            p = os.path.join(root, fn)
            lines = open(p, encoding="utf-8", errors="replace").read().splitlines()
            for i, line in enumerate(lines):
                if "uses:" not in line or "actions/checkout@" not in line:
                    continue
                uses_indent = len(line) - len(line.lstrip())
                for nxt in lines[i + 1: i + 9]:
                    stripped = nxt.strip()
                    if not stripped or stripped.startswith("#"):
                        continue
                    ind = len(nxt) - len(nxt.lstrip())
                    if stripped != "with:" and ind <= uses_indent:
                        break  # left the step's with: block
                    if ind > uses_indent and stripped.startswith("path:"):
                        val = stripped.split(":", 1)[1].strip().strip("'\"")
                        if "${{" in val:
                            unresolvable.append(f"{p}: {val}")
                        elif val.startswith("/") or val in (".", "./"):
                            unresolvable.append(f"{p}: {val} (absolute/self)")
                        else:
                            prefixes.add(val.rstrip("/") + "/")
                        break
                    if stripped.startswith(("- ", "uses:", "name:", "-name")):
                        break  # new step/entry, no path:
                    if ":" not in stripped:
                        break
    # action.yml at repo root (composite) can also carry checkout steps
    for extra in ("action.yml",):
        if os.path.isfile(extra):
            # composite actions run against the CALLER's checkout; a
            # path: here would be unusual. Scan with the same rule.
            lines = open(extra, encoding="utf-8", errors="replace").read().splitlines()
            for i, line in enumerate(lines):
                if "uses:" in line and "actions/checkout@" in line:
                    for nxt in lines[i + 1: i + 9]:
                        s = nxt.strip()
                        if s.startswith("path:"):
                            v = s.split(":", 1)[1].strip().strip("'\"")
                            if "${{" not in v and not v.startswith("/"):
                                prefixes.add(v.rstrip("/") + "/")
                            break
    for u in unresolvable:
        print(f"NOTE: checkout path not text-resolvable, leg D cannot match it: {u}")
    return prefixes


def check_ignore_rc(path):
    """Prevention authority: `git check-ignore --no-index -q` on a PROBE
    path (never on the index). Returns git's rc: 0 = some ignore rule
    covers it, 1 = uncovered, >1 = the authority itself errored."""
    r = subprocess.run(["git", "check-ignore", "--no-index", "-q", path],
                       capture_output=True, text=True)
    return r.returncode


def main():
    if len(sys.argv) > 1:
        print(__doc__.strip().splitlines()[-1])
        return 2
    fails = 0
    files = tracked_files()

    # A. generated-file blocklist
    hits = sorted(set(files) & BLOCKLIST)
    for h in hits:
        print(f"FAIL: generated CI byproduct is tracked: {h}")
        fails += 1
    if not hits:
        print(f"OK: 0/{len(BLOCKLIST)} generated byproducts tracked")

    # B. scratch-name sweep: any tracked *.log / *.out at any depth
    scratch = sorted(f for f in files if f.endswith((".log", ".out")))
    for s in scratch:
        print(f"FAIL: tracked scratch log: {s}")
        fails += 1
    if not scratch:
        print("OK: no tracked *.log / *.out anywhere")

    # C. tracked .md outside proofs/ must be an allowed doc
    stray = sorted(
        f for f in files
        if f.endswith(".md") and not f.startswith("proofs/")
        and f not in DOC_ALLOW
    )
    for s in stray:
        print(f"FAIL: tracked .md outside proofs/ not in DOC_ALLOW: {s}")
        fails += 1
    if not stray:
        print("OK: tracked .md set == proofs/ receipts + DOC_ALLOW docs")

    # D. checkout-path inventory (derived, not hand-listed): any tracked
    # file under a job-level actions/checkout `path:` prefix is a tracked
    # clone byproduct. OK-line PRINTS the derived set (c38 announce-
    # yourself: a derived carve-out that prints nothing is a hole with a
    # name).
    prefixes = checkout_paths()
    dhits = sorted(f for f in files
                   if any(f.startswith(p) for p in prefixes))
    for h in dhits:
        print(f"FAIL: tracked file under a CI checkout path: {h}")
        fails += 1
    print(f"OK: checkout-path legs derived {sorted(prefixes)}"
          if not dhits else
          f"checkout-path prefixes scanned: {sorted(prefixes)}")

    # E. catch-vs-prevent parity: leg A/D names CATCH the accident; an
    # ignore rule PREVENTS it. Authority is check-ignore --no-index (the
    # index is irrelevant to what `git add -A` would do). Leg-D prefixes
    # are probed as CHILD paths (dir-only rules don't match the bare dir;
    # measured on my own .gitignore: '.ethkey-tools/' rc=0, bare rc=1).
    # rc>1 names the crash and exits 2 — never a silent skip, never a
    # verdict wearing an error.
    efail = 0
    probes = sorted(BLOCKLIST) + sorted(p + "probe" for p in prefixes)
    for probe in probes:
        rc = check_ignore_rc(probe)
        if rc > 1:
            print(f"FAIL: check-ignore on '{probe}' errored rc={rc} "
                  "(authority broken, not a verdict)")
            sys.exit(2)
        if rc == 1:
            print(f"FAIL: catch-without-prevent: '{probe}' is a "
                  f"generated-byproduct path with NO ignore rule "
                  f"(a bare `git add -A` would re-track it)")
            fails += 1
            efail += 1
    if not efail:
        print(f"OK: catch-vs-prevent parity: {len(probes)}/{len(probes)} "
              f"byproduct paths covered by an ignore rule "
              f"({len(BLOCKLIST)} names + {len(prefixes)} derived prefixes)")

    if fails:
        print(f"artifact-hygiene: {fails} violation(s)")
        return 1
    print("artifact-hygiene: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
